version: '3.1'
services:

  nginx:
    image: nginx:1.15
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web/build:/var/www/html
      - ./api/files:/var/www/html/files
    ports:
      - "80:80"
    restart: always
    depends_on:
      - api

  api:
    image: node:14
    volumes:
      - ./api:/usr/src/app
    command: npm run start:dev
    working_dir: /usr/src/app/
    restart: always
    depends_on:
      - db
    links:
      - db


  build:
    build: "./build"
    volumes:
      - "./web:/usr/src/app/web"
      - "./api:/usr/src/app/api"
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:11
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  myadmin:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    restart: always
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - "./elastic:/usr/share/elasticsearch/data"
    depends_on:
      - api
    links:
      - api